# Generated by Django 2.1.11 on 2020-04-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0004_auto_20200410_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
